server:
    port: 8080
    contextPath: /bingo/


security.basic.enable: false
security.enable-csrf: false
management.security.enabled: false

---
spring:
    profiles: local,default
datasource:
    bingo:
        url: jdbc:mysql://localhost:3306/bingo
        username: root
        password: rabbit
        driverClassName: com.mysql.jdbc.Driver
        defaultSchema:
        hibernate:
            hbm2ddl.method: update
            show_sql: true
            format_sql: true
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
